### ISSUE TITLE
Test Script Failed with (null)

### ISSUE THREAD

**Issue by nicnocquee** [bendyworks/bwoken#26]
Not sure what happened here, when I run `rake iphone --trace`, simulator didn't run and I got this

```
** Invoke iphone (first_time)
** Invoke iphone:test (first_time)
** Invoke integration/tmp/results (first_time, not_needed)
** Invoke coffeescript (first_time)
** Invoke integration/tmp/javascript/iphone/example.js (first_time, not_needed)
** Invoke integration/tmp/javascript/iphone (first_time, not_needed)
** Invoke integration/coffeescript/iphone/example.coffee (first_time, not_needed)
** Invoke integration/coffeescript/iphone (first_time, not_needed)
** Invoke integration/tmp/javascript/example_js.js (first_time, not_needed)
** Invoke integration/tmp/javascript (first_time, not_needed)
** Invoke integration/javascript/example_js.js (first_time, not_needed)
** Invoke integration/javascript (first_time, not_needed)
** Execute coffeescript
** Execute iphone:test

iphone  example.js
:   (null)
rake aborted!
Test Script Failed
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/bwoken-1.3.0/lib/bwoken/script.rb:88:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/bwoken-1.3.0/lib/bwoken/script.rb:32:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/bwoken-1.3.0/lib/bwoken/script.rb:20:in `block in run_all'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/bwoken-1.3.0/lib/bwoken/script.rb:19:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/bwoken-1.3.0/lib/bwoken/script.rb:19:in `run_all'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/bwoken-1.3.0/lib/bwoken/tasks/bwoken.rake:82:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/task.rb:236:in `block in execute'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/task.rb:231:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/task.rb:195:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/task.rb:195:in `invoke_prerequisites'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/task.rb:161:in `invoke'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/application.rb:106:in `block in top_level'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/application.rb:100:in `top_level'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p392/gems/rake-10.1.0/bin/rake:33:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p392/bin/rake:19:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p392/bin/rake:19:in `<main>'
/usr/local/rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
```

OSX 10.8.4
Xcode 4.6.3 (4H1503)

Help, please....

**Comment by listrophy** [comment]
Did it hang there? Or did it just immediately spit all that stuff out?

**Comment by nicnocquee** [comment]
immediately @listrophy

**Comment by listrophy** [comment]
@nicnocquee sorry about the silence on this. Once the next release is available, I'll ask you to run it again with the `--formatter=passthru` option enabled, so you don't get the cryptic ": (null)" error message.
