### ISSUE TITLE
Run Bwoken on OS X Server for CI

### ISSUE THREAD

**Issue by victoriazheng** [bendyworks/bwoken#44]
I don't know if anyone as tried to run Bwoken as a post-action in build scheme, I was trying out that today so we could run UI test on OS X Server, but I've run into this weird error says `invalid byte sequence in US-ASCII (ArgumentError)`

I've tried to add encoding info into my own Gemfile but that didn't work. And this doesn't happen if I run Bwoken locally on my machine.

The full error message

``` ruby
/Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0.beta.1/lib/bwoken/formatter.rb:29:in `line_demuxer': invalid byte sequence in US-ASCII (ArgumentError)
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0.beta.1/lib/bwoken/formatter.rb:65:in `block in format'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0.beta.1/lib/bwoken/formatter.rb:64:in `each_line'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0.beta.1/lib/bwoken/formatter.rb:64:in `format'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0.beta.1/lib/bwoken/script.rb:54:in `block in run'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:217:in `popen_run'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:99:in `popen3'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0.beta.1/lib/bwoken/script.rb:53:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0.beta.1/lib/bwoken/device_runner.rb:17:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0.beta.1/lib/bwoken/device_runner.rb:17:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0.beta.1/lib/bwoken/script_runner.rb:55:in `execute_on_device'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0.beta.1/lib/bwoken/script_runner.rb:22:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0.beta.1/lib/bwoken/cli/test.rb:103:in `test'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0.beta.1/lib/bwoken/cli/test.rb:65:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0.beta.1/lib/bwoken/cli.rb:52:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0.beta.1/bin/bwoken:3:in `<top (required)>'
    from /usr/bin/bwoken:23:in `load'
    from /usr/bin/bwoken:23:in `<main>'
```

**Comment by listrophy** [comment]
Could you install [rvm](http://rvm.io/) and try again?

**Comment by victoriazheng** [comment]
I did install rvm but I had to do Multi-User Installation under another user account instead of the normal one because of permission issues with the OS X Server user

**Comment by victoriazheng** [comment]
Just in case someone else run into this issue, you can install rvm using multi-user installation (using sudo), and do the other install steps as specified in readme doc. If you run into the error I had, try adding the following code to your Gemfile. I tried this the other day but somehow it didn't work, I just uninstalled everything and reinstalled and this code snipet worked :)

``` ruby
if RUBY_VERSION =~ /2.0/ # assuming you're running Ruby ~2.0
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
end
```
