### ISSUE TITLE
Document Missing Template Error

### ISSUE THREAD

**Issue by ghost** [bendyworks/bwoken#75]
trying to run my ios app test installation, I get the following error : 

```
macMini:OAuthClientSetup yves$ bwoken init
macMini:OAuthClientSetup yves$ bwoken test
Building............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Build Successful!

iphone  example.js
:   Failed to load document 'file:///Users/yves/Developpement/iOS7/rails_clients/OAuthClientSetup/integration/tmp/trace.trace/' : (Error Domain=com.apple.instruments Code=-6 "Document Missing Template Error: The operation couldn’t be completed. (com.apple.instruments error -6.)")
/Users/yves/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bwoken-2.0.0/lib/bwoken/script.rb:55:in `block in run': Test Script Failed (Bwoken::ScriptFailedError)
    from /Users/yves/.rbenv/versions/2.1.2/lib/ruby/2.1.0/open3.rb:199:in `popen_run'
    from /Users/yves/.rbenv/versions/2.1.2/lib/ruby/2.1.0/open3.rb:93:in `popen3'
    from /Users/yves/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bwoken-2.0.0/lib/bwoken/script.rb:53:in `run'
    from /Users/yves/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bwoken-2.0.0/lib/bwoken/simulator_runner.rb:21:in `each'
    from /Users/yves/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bwoken-2.0.0/lib/bwoken/simulator_runner.rb:21:in `execute'
    from /Users/yves/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bwoken-2.0.0/lib/bwoken/script_runner.rb:33:in `execute_for_family'
```

**Comment by listrophy** [comment]
Assuming you are on Xcode 6.x, please try version 2.1.0.rc.1. See: https://github.com/bendyworks/bwoken/issues/76#issuecomment-56964853

**Comment by roopesh85** [comment]
Hi ,

I used 2.1.0.rc.2 and i still see the issue . 

Instruments Trace Error : Failed to load template 'Automation/ -- file:///Users/roopeshkumar/repo/assetoperation/' (Error Domain=com.apple.instruments Code=-6 "Document Missing Template Error: The operation couldn’t be completed. (com.apple.instruments error -6.)")
/Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/gems/bwoken-2.1.0.rc.2/lib/bwoken/script.rb:60:in `block in run': Test Script Failed (Bwoken::ScriptFailedError)
    from /Users/roopeshkumar/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/open3.rb:217:in`popen_run'
    from /Users/roopeshkumar/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/open3.rb:99:in `popen3'
    from /Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/gems/bwoken-2.1.0.rc.2/lib/bwoken/script.rb:58:in`run'
    from /Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/gems/bwoken-2.1.0.rc.2/lib/bwoken/simulator_runner.rb:22:in `each'
    from /Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/gems/bwoken-2.1.0.rc.2/lib/bwoken/simulator_runner.rb:22:in`execute'
    from /Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/gems/bwoken-2.1.0.rc.2/lib/bwoken/script_runner.rb:34:in `execute_for_family'
    from /Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/gems/bwoken-2.1.0.rc.2/lib/bwoken/script_runner.rb:29:in`block in execute_in_simulator'
    from /Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/gems/bwoken-2.1.0.rc.2/lib/bwoken/script_runner.rb:28:in `each'
    from /Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/gems/bwoken-2.1.0.rc.2/lib/bwoken/script_runner.rb:28:in`execute_in_simulator'
    from /Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/gems/bwoken-2.1.0.rc.2/lib/bwoken/script_runner.rb:21:in `execute'
    from /Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/gems/bwoken-2.1.0.rc.2/lib/bwoken/cli/test.rb:114:in`test'
    from /Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/gems/bwoken-2.1.0.rc.2/lib/bwoken/cli/test.rb:72:in `run'
    from /Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/gems/bwoken-2.1.0.rc.2/lib/bwoken/cli.rb:58:in`<top (required)>'
    from /Users/roopeshkumar/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `require'
    from /Users/roopeshkumar/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:128:in`rescue in require'
    from /Users/roopeshkumar/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require'
    from /Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/gems/bwoken-2.1.0.rc.2/bin/bwoken:3:in`<top (required)>'
    from /Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/bin/bwoken:23:in `load'
    from /Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/bin/bwoken:23:in`<main>'
    from /Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/bin/ruby_executable_hooks:15:in `eval'
    from /Users/roopeshkumar/.rvm/gems/ruby-2.0.0-p598@Asset Ops UI Automation/bin/ruby_executable_hooks:15:in`<main>'

whers is it looking for template file ? can you guide ..

**Comment by Vovannking** [comment]
Hello, 

I have the same error. Bwoken-2.1.0.rc.2, Xcode 6.2, OSX 10.10.3
Will be very grateful to hear any suggestions.

*\* BUILD SUCCEEDED **

2015-03-18 10:05:42.322 instruments[14518:45447] WebKit Threading Violation - initial use of WebKit from a secondary thread.
Instruments Trace Error : Failed to load document 'file:///Users/vovanking/Development/rd2/integration/tmp/trace.trace/' : (Error Domain=com.apple.instruments Code=-6 "Document Missing Template Error: The operation couldn’t be completed. (com.apple.instruments error -6.)")
/Users/vovanking/.rvm/gems/ruby-2.2.0@rd2/gems/bwoken-2.1.0.rc.2/lib/bwoken/script.rb:60:in `block in run': Test Script Failed (Bwoken::ScriptFailedError)
    from /Users/vovanking/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open3.rb:199:in`popen_run'
    from /Users/vovanking/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open3.rb:93:in `popen3'
    from /Users/vovanking/.rvm/gems/ruby-2.2.0@rd2/gems/bwoken-2.1.0.rc.2/lib/bwoken/script.rb:58:in`run'
    from /Users/vovanking/.rvm/gems/ruby-2.2.0@rd2/gems/bwoken-2.1.0.rc.2/lib/bwoken/device_runner.rb:18:in `each'
    from /Users/vovanking/.rvm/gems/ruby-2.2.0@rd2/gems/bwoken-2.1.0.rc.2/lib/bwoken/device_runner.rb:18:in`execute'
    from /Users/vovanking/.rvm/gems/ruby-2.2.0@rd2/gems/bwoken-2.1.0.rc.2/lib/bwoken/script_runner.rb:57:in `execute_on_device'
    from /Users/vovanking/.rvm/gems/ruby-2.2.0@rd2/gems/bwoken-2.1.0.rc.2/lib/bwoken/script_runner.rb:23:in`execute'
    from /Users/vovanking/.rvm/gems/ruby-2.2.0@rd2/gems/bwoken-2.1.0.rc.2/lib/bwoken/cli/test.rb:114:in `test'
    from /Users/vovanking/.rvm/gems/ruby-2.2.0@rd2/gems/bwoken-2.1.0.rc.2/lib/bwoken/cli/test.rb:72:in`run'
    from /Users/vovanking/.rvm/gems/ruby-2.2.0@rd2/gems/bwoken-2.1.0.rc.2/lib/bwoken/cli.rb:58:in `<top (required)>'
    from /Users/vovanking/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in`require'
    from /Users/vovanking/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
    from /Users/vovanking/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in`require'
    from /Users/vovanking/.rvm/gems/ruby-2.2.0@rd2/gems/bwoken-2.1.0.rc.2/bin/bwoken:3:in `<top (required)>'
    from /Users/vovanking/.rvm/gems/ruby-2.2.0@rd2/bin/bwoken:23:in`load'
    from /Users/vovanking/.rvm/gems/ruby-2.2.0@rd2/bin/bwoken:23:in `<main>'
    from /Users/vovanking/.rvm/gems/ruby-2.2.0@rd2/bin/ruby_executable_hooks:15:in`eval'
    from /Users/vovanking/.rvm/gems/ruby-2.2.0@rd2/bin/ruby_executable_hooks:15:in `<main>'
