### ISSUE TITLE
bwoken init error with latest

### ISSUE THREAD

**Issue by yairgo** [bendyworks/bwoken#89]
The latest release candidate is broken with the default bundle install.

This appears to be because slop released a new version 4.0.0
I added 
`gem 'slop', '3.6.0'`
to my Gemfile and the init command worked successfully

**Comment by dcx** [comment]
I experienced this too while following the introductory install instructions, this fix worked. Thanks yairgo!

**Comment by grabbou** [comment]
Confirmed. Thanks for sorting that out @yairgo

**Comment by AlexDS85** [comment]
yeah - it works.

**Comment by extr3mal** [comment]
Using rake 10.4.2
Using coffee-script-source 1.9.1
Using colorful 0.0.3
Using execjs 2.3.0
Using json_pure 1.8.2
Using slop 3.6.0
Using bwoken 2.1.0.rc.2 (was 2.1.0.rc.1)
Using bundler 1.8.2
Bundle complete! 2 Gemfile dependencies, 8 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

Then when i type in bwoken --version

Valik:rd2 user$ bwoken --version
/Library/Ruby/Gems/2.0.0/gems/bwoken-2.1.0.rc.2/lib/bwoken/cli.rb:10:in `block in <top (required)>': undefined method`on' for main:Object (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/slop-4.0.0/lib/slop/options.rb:33:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/slop-4.0.0/lib/slop.rb:24:in`new'
    from /Library/Ruby/Gems/2.0.0/gems/slop-4.0.0/lib/slop.rb:24:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.1.0.rc.2/lib/bwoken/cli.rb:9:in`<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in`require'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.1.0.rc.2/bin/bwoken:3:in `<top (required)>'
    from /usr/bin/bwoken:23:in`load'
    from /usr/bin/bwoken:23:in `<main>'

**Comment by roopesh85** [comment]
yes , even i see this error .

Ignoring xcodeproj-0.17.0 because its extensions are not built.  Try: gem pristine xcodeproj-0.17.0
/Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0/lib/bwoken/cli.rb:10:in `block in <top (required)>': undefined method`on' for main:Object (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/slop-4.0.0/lib/slop/options.rb:33:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/slop-4.0.0/lib/slop.rb:24:in`new'
    from /Library/Ruby/Gems/2.0.0/gems/slop-4.0.0/lib/slop.rb:24:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0/lib/bwoken/cli.rb:9:in`<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in`require'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0/bin/bwoken:3:in `<top (required)>'
    from /usr/bin/bwoken:23:in`load'
    from /usr/bin/bwoken:23:in `<main>'

can some one help me ?

**Comment by AlexDS85** [comment]
as you see - it still use slop v4 - so you need to uninstall it - and install only slop v 3.x.x

**Comment by extr3mal** [comment]
sudo gem uninstall slop --version 4.0.0 

removed issue

**Comment by roopesh85** [comment]
thank you extr3mal  .. it worked for me :)
