### ISSUE TITLE
bwoken doesn't run

### ISSUE THREAD

**Issue by ghost** [bendyworks/bwoken#90]
When I start to run bwoken I get

```
/Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0/lib/bwoken/cli.rb:10:in `block in <top (required)>': undefined method `on' for main:Object (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/slop-4.0.0/lib/slop/options.rb:33:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/slop-4.0.0/lib/slop.rb:24:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/slop-4.0.0/lib/slop.rb:24:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0/lib/bwoken/cli.rb:9:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/bwoken-2.0.0/bin/bwoken:3:in `<top (required)>'
    from /usr/bin/bwoken:23:in `load'
    from /usr/bin/bwoken:23:in `<main>'
```

I am not root so I tried the `sudo gem install bwoken && bwoken init` method, could that be the problem?

Thanks and regards,
Sebastian Mecklenburg

**Comment by AlexDS85** [comment]
I have the same issue... seems like it is due to slop v.4 ... keep fighting with it:)

**Comment by roopesh85** [comment]
HI  Guys, 

Ny update on this ? even i am stuck with the same issue,

**Comment by AlexDS85** [comment]
https://github.com/bendyworks/bwoken/issues/89 look at this issue - here is a solution:)
